# Generated by Django 6.0.5 on 2026-06-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="congratulation_sent",
            field=models.BooleanField(default=False),
        ),
    ]
