# Generated by Django 6.0.5 on 2026-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_congratulation_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="congratulation_sent",
            field=models.BooleanField(default=False, verbose_name="Поздравление отправлено"),
        ),
    ]
