# Generated by Django 6.0.5 on 2026-06-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blogpost_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_manage_blog", "Может управлять блогом")],
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
    ]
